version: "3"

services:
  db:
    image: postgres:13.13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manga
    ports:
      - "5432:5432"
